# CREATE USER 'spoons'@'localhost' IDENTIFIED BY 'spoons_be_good';
# GRANT ALL ON spoons_production.* TO 'spoons'@'localhost';
# GRANT ALL ON spoons_test.* TO 'spoons'@'localhost';
# GRANT ALL ON spoons_development.* TO 'spoons'@'localhost';

development:
  adapter: mysql2
  encoding: utf8
  database: spoons_development
  username: spoons
  password: spoons_be_good
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: spoons_test
  username: spoons
  password: spoons_be_good
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: spoons_development
  username: spoons
  password: spoons_be_good
  host: localhost
  port: 3306